[[TC-02-DS-014](../../tests/TS-03_Data_acquisition_and_management/TS-DS-014#tc-02-ds-014-positive-test--no-owned-datasets)] Test log 12-06-2025 11:29:55
---
‚ùå Failed: authenticated user is not able to see ,,Owned sets''.

[error](images/error_TC-02-DS-014.png)

**Steps to reproduce:**
- log in as ,,Data supplier''
- click ,,Go to Page'' under ,,Owned sets''

